id - {.id}
interface - {interface}
mac-address - {mac-address}
ap - {ap}
wds - {wds}
bridge - {bridge}
rx - {rx-rate}
tx - {tx-rate}
packs - {packets}
bytes - {bytes}
frames - {frames}
fr-by - {frame-bytes}
hw-frames - {hw-frames}
hw-frame-bytes - {hw-frame-bytes}
tx-frames-timed-out - {tx-frames-timed-out}
uptime - {uptime}
last-activity - {last-activity}
signal-strength - {signal-strength}
signal-to-noise - {signal-to-noise}
signal-strength-ch0 - {signal-strength-ch0}
strength-at-rates - {strength-at-rates}
tx-ccq - {tx-ccq}
p-throughput - {p-throughput}
distance - {distance}
last-ip - {last-ip}
802.1x-port-enabled - {802.1x-port-enabled}
authentication-type - {authentication-type}
encryption - {encryption}
group-encryption - {group-encryption}
management-protection - {management-protection}
wmm-enabled - {wmm-enabled}
tx-rate-set - {tx-rate-set}